---
# Common tasks

- name: Install common packages
  yum : name={{ item }} state=installed
  with_items:
   - libselinux-python
   - policycoreutils
   - policycoreutils-python
   - ntp
   - ruby-devel

- name: make sure we have the right time
     shell: ntpdate -u 0.centos.pool.ntp.org

- name: start the ntp service
     service: name=ntpd state=started enabled=yes