---
# Common tasks

- name: Install common packages
  yum : name={{ item }} state=present
  with_items:
   - libselinux-python
   - policycoreutils
   - policycoreutils-python
   - ntp
   - ruby
   - unzip
   - curl
   - wget
   - augeas-1.0.0-5.el6.x86_64
   - ruby-devel

- name: Install broker packages
  tags: install
  yum : name={{ item }} state=present
  with_items:
    - bind-9.8.2-0.17.rc1.el6_4.6.x86_64
    - httpd-tools-2.2.15-29.el6.centos.x86_64

# setup EPEL
- name: download epel-release-6-8.noarch.rpm
  get_url: url=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm dest=/root/epel-release-6-8.noarch.rpm

- name: add EPEL repository
  yum : name=/root/epel-release-6-8.noarch.rpm state=present
  #command: rpm -Uvh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm


# setup ruby193 SCL
- name: Setup ruby193 SCL
  tags: install
  copy: src={{ item }} dest=/etc/yum.repos.d/{{ item }} backup=yes force=no
  with_items:
      - openshift-origin-deps.repo
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install broker packages
  tags: install
  yum : name=ruby193-ruby state=present


# time
- name: make sure we have the right time
  shell: ntpdate -u 0.centos.pool.ntp.org

- name: start the ntp service
  service: name=ntpd state=started enabled=yes

#
- name: SELinux Enforcing (Targeted)
  selinux: policy=targeted state=enforcing

- name: reboot the servers to be sure that SELinux is enabled
  shell: reboot

- name: Wait for server to restart
  local_action:
    module: wait_for
      port=22
      delay=20
      timeout=600